/**
 * Returns a cleansed list of the IGDB response data objects that has
 * removed games that the service matched by title, but I do not own
 * for a given platform.
 * 
 * Example: in the test for this function, the mock data illustrates
 * "Adventure" as two separate entries, one for the Atari 2600 and a
 * second for the BBC Mircroprocesser, however I only own the game for
 * the Atari.
 * 
 * @param {Array} sourceList list generated by loadGames() in clz import
 * @param {*} dupeList list of "results" from igdb multiquery response
 */
export const dedupeTitleByPlatform = (sourceList, dupeList) => {
  const dedupedList = []
  for(var i = 0; i < sourceList.length; i++) {
    const sourceListPlatform = sourceList[i].platform
    for(var j = 0; j < dupeList.length; j++) {
      if(sourceList[i].title === dupeList[j].name) {
        for(var k = 0; k < dupeList[j].platforms.length; k++) {
          const dupeListPlatform = dupeList[j].platforms[k].name
          if(dupeListPlatform.includes(sourceListPlatform)) {
            dedupedList.push(dupeList[j])
            break
          }
        }
      }
    }
  }
  return dedupedList
}